steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: create-image-name
    entrypoint: 'bash'
    dir: merged/frontend
    args:
      - '-c'
      - |
        echo "gcr.io/$PROJECT_ID/frontend:$BRANCH_NAME-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - name: 'gcr.io/cloud-builders/docker'
    id: build-if-master
    entrypoint: 'bash'
    dir: merged/frontend
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker build -t $image .
        else
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/docker'
    id: push-if-master
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-if-master
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]
        then
          image=$(cat /workspace/imagename)
          gcloud run deploy frontend --image $image --region northamerica-northeast1 --platform managed
        else
          exit 0
        fi
